<?php

define('BUTLER_BLOCKS_DEFAULT_CONTEXT', '-- default --');

function butler_blocks_menu() {
  $items = array();

  $items['administer/displays'] = array(
    'title' => 'Displays',
    'page callback' => '',
    'access arguments' => array('access content'),
  );

  $items['administer/displays/display/%butler_blocks_display'] = array(
    'title' => 'Displays',
    'page callback' => '',
    'access arguments' => array('access content'),
  );

  return $items;
}

function butler_blocks_menu_alter(&$items) {
  db_query('DELETE FROM {butler_blocks_display_cache}');
  $query = db_query('SELECT did, url FROM {butler_blocks_display}');
  $displays = array();
  foreach ($query as $display) {
    $displays[$display->url][] = $display->did;
  }
  foreach ($displays as $url => $displays) {
    if (isset($items[$url])) {
      $item = $items[$url];
    }
    else {
      $item = FALSE;
    }
    $displays['default'] = $item;
    $cache = db_insert('butler_blocks_display_cache')->fields(array(
      'data' => serialize($displays),
    ))->execute();
    $items[$url] = array(
      'title callback' => 'butler_blocks_page_title',
      'title arguments' => array($cache),
      'page callback' => 'butler_blocks_page_callback',
      'access callback' => 'butler_blocks_access_callback',
      'access arguments' => array($cache),
    );
  }
}

function butler_blocks_display_load($did) {
  $display = db_query('SELECT did, url, data FROM {butler_blocks_display} WHERE did = :did', array(':did' => $did))->fetch();
  $display = drupal_unpack($display);
  $class = 'ButlerBlocksDisplay_' . $display->type;
  return new $class($display, butler_context());
}

function _butler_blocks_active_display($cid = NULL) {
  static $cache_display;
  if (isset($cache_display)) {
    return $cache_display;
  }
  if (!$cid) {
    return FALSE;
  }
  $displays = unserialize(db_query('SELECT data FROM {butler_blocks_display_cache} WHERE cid = :cid', array(':cid' => $cid))->fetch()->data);
  $default = $displays['default'];
  unset($displays['default']);
  foreach ($displays as $did) {
    $display = butler_blocks_display_load($did);
    if ($display->active()) {
      $cache_display = $display;
      return $display;
    }
  }
  $cache_display = new ButlerBlocksDisplay_default($default, butler_context());
  return $cache_display;
}

function butler_blocks_page_title($cid) {
  $display = _butler_blocks_active_display($cid);
  return $display->title();
}

function butler_blocks_access_callback($cid) {
  return TRUE;
}

function butler_blocks_page_callback() {
  return '';
}

class ButlerBlocksDisplay {
  function __construct($data, $context) {
    $this->data = $data;
    $this->context = $context;
  }
  function render(&$page) {
    foreach ($this->data->blocks as $block) {
      $context = clone $this->context;
      foreach ($block['contexts'] as $name => $value) {
        if ($value != BUTLER_BLOCKS_DEFAULT_CONTEXT) {
          $class = 'ButlerContext_' . $name;
          $object = new $class;
          $object->set($value);
          $context->set($name, $object);
        }
      }
      $class = 'ButlerBlocksBlock_' . $block['type'];
      $object = new $class($context);
      $page[$block['region']][] = $object->render();
    }
  }
}

class ButlerBlocksBlock {
  function __construct($context) {
    $this->context = $context;
  }
}

function butler_blocks_init() {
  /*
  db_query('TRUNCATE {butler_blocks_display}');
  db_query('INSERT INTO {butler_blocks_display} (url, data) VALUES (:url, :data)', array(':url' => 'node/%node', ':data' => serialize(array(
    'type' => 'node_type',
    'node_type' => 'page',
    'blocks' => array(
      array(
        'region' => 'content',
        'type' => 'node_content',
        'contexts' => array('node' => BUTLER_BLOCKS_DEFAULT_CONTEXT),
      ),
      array(
        'region' => 'sidebar_first',
        'type' => 'node_content',
        'contexts' => array('node' => 2),
      ),
    ),
  ))));
  */
  //menu_rebuild();
  //module_implements('', FALSE, TRUE);
  //registry_rebuild();
}

/**
 * Implements hook_page_build().
 */
function butler_blocks_page_build(&$page) {
  global $theme;
  if ($display = _butler_blocks_active_display()) {
    $display->render($page);
  }
}
